name: Update package version
on:
  pull_request:
  merge_group:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update version
        run: |
          npm run version
    